server:
  port: 8084
  servlet:
    context-path: /api/v1
  #files
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: senadoiud
  # Conexión a BD
  datasource:
    url: jdbc:mysql://localhost:3306/senado_iud?createDatabaseIfNotExist=true
    username: root
    password: 1234
  # Generar tablas con código Java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true


  # Envío de Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: felipe.fernandezr@est.iudigital.edu.co
    password: <ingrese la contraseña aquí>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#spring security
security:
  jwt:
    client-service: SenadoIUD
    password-service: 123456
    scope-read: read
    scope-write: write
    grant-password: password
    grant-refresh: refresh_token
    token-validity-seconds: 3600
    refresh-validity-seconds: 3600